-- query 1
SELECT category.name, COUNT(*) AS number_of_films
FROM sakila.category AS category
JOIN sakila.film_category AS film_category
ON category.category_id = film_category.category_id
JOIN sakila.film AS film
ON film_category.film_id = film.film_id
GROUP BY category.name;


-- query 2: store ID, city, and country for each store.
SELECT store.store_id, city.city, country.country
FROM sakila.store AS store
LEFT JOIN sakila.address AS address ON address.address_id = store.address_id
JOIN sakila.city AS city ON city.city_id = address.city_id
JOIN sakila.country AS country ON country.country_id = city.country_id;

-- query 3 : Calculate the total revenue generated by each store in dollars.
SELECT store.store_id, SUM(payment.amount)
FROM sakila.payment AS payment
JOIN sakila.staff AS staff ON staff.staff_id = payment.staff_id
JOIN sakila.store AS store ON store.store_id = staff.store_id
GROUP BY store.store_id;

-- query 4: Determine the average running time of films for each category.
SELECT category.name, AVG(film.length) AS number_of_films
FROM sakila.category AS category
JOIN sakila.film_category AS film_category
ON category.category_id = film_category.category_id
JOIN sakila.film AS film
ON film_category.film_id = film.film_id
GROUP BY category.name;

-- bonus 1 : Identify the film categories with the longest average running time

SELECT category.name, AVG(film.length) AS average_duration
FROM sakila.category AS category
JOIN sakila.film_category AS film_category
ON category.category_id = film_category.category_id
JOIN sakila.film AS film
ON film_category.film_id = film.film_id
GROUP BY category.name
ORDER BY 2 DESC
LIMIT 1;








